# Generated by Django 2.0.5 on 2018-09-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=32, verbose_name='教室')),
                ('lesson_0102', models.CharField(max_length=64, verbose_name='0102')),
                ('lesson_0304', models.CharField(max_length=64, verbose_name='0304')),
                ('lesson_05', models.CharField(max_length=64, verbose_name='05')),
                ('lesson_0607', models.CharField(max_length=64, verbose_name='0607')),
                ('lesson_0809', models.CharField(max_length=64, verbose_name='0809')),
                ('lesson_10', models.CharField(max_length=64, verbose_name='10')),
                ('lesson_1112', models.CharField(max_length=64, verbose_name='1112')),
                ('lesson_13', models.CharField(max_length=64, verbose_name='13')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=32, verbose_name='教室')),
                ('lesson_0102', models.CharField(max_length=64, verbose_name='0102')),
                ('lesson_0304', models.CharField(max_length=64, verbose_name='0304')),
                ('lesson_05', models.CharField(max_length=64, verbose_name='05')),
                ('lesson_0607', models.CharField(max_length=64, verbose_name='0607')),
                ('lesson_0809', models.CharField(max_length=64, verbose_name='0809')),
                ('lesson_10', models.CharField(max_length=64, verbose_name='10')),
                ('lesson_1112', models.CharField(max_length=64, verbose_name='1112')),
                ('lesson_13', models.CharField(max_length=64, verbose_name='13')),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=32, verbose_name='教室')),
                ('lesson_0102', models.CharField(max_length=64, verbose_name='0102')),
                ('lesson_0304', models.CharField(max_length=64, verbose_name='0304')),
                ('lesson_05', models.CharField(max_length=64, verbose_name='05')),
                ('lesson_0607', models.CharField(max_length=64, verbose_name='0607')),
                ('lesson_0809', models.CharField(max_length=64, verbose_name='0809')),
                ('lesson_10', models.CharField(max_length=64, verbose_name='10')),
                ('lesson_1112', models.CharField(max_length=64, verbose_name='1112')),
                ('lesson_13', models.CharField(max_length=64, verbose_name='13')),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=32, verbose_name='教室')),
                ('lesson_0102', models.CharField(max_length=64, verbose_name='0102')),
                ('lesson_0304', models.CharField(max_length=64, verbose_name='0304')),
                ('lesson_05', models.CharField(max_length=64, verbose_name='05')),
                ('lesson_0607', models.CharField(max_length=64, verbose_name='0607')),
                ('lesson_0809', models.CharField(max_length=64, verbose_name='0809')),
                ('lesson_10', models.CharField(max_length=64, verbose_name='10')),
                ('lesson_1112', models.CharField(max_length=64, verbose_name='1112')),
                ('lesson_13', models.CharField(max_length=64, verbose_name='13')),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=32, verbose_name='教室')),
                ('lesson_0102', models.CharField(max_length=64, verbose_name='0102')),
                ('lesson_0304', models.CharField(max_length=64, verbose_name='0304')),
                ('lesson_05', models.CharField(max_length=64, verbose_name='05')),
                ('lesson_0607', models.CharField(max_length=64, verbose_name='0607')),
                ('lesson_0809', models.CharField(max_length=64, verbose_name='0809')),
                ('lesson_10', models.CharField(max_length=64, verbose_name='10')),
                ('lesson_1112', models.CharField(max_length=64, verbose_name='1112')),
                ('lesson_13', models.CharField(max_length=64, verbose_name='13')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=32, verbose_name='教室')),
                ('lesson_0102', models.CharField(max_length=64, verbose_name='0102')),
                ('lesson_0304', models.CharField(max_length=64, verbose_name='0304')),
                ('lesson_05', models.CharField(max_length=64, verbose_name='05')),
                ('lesson_0607', models.CharField(max_length=64, verbose_name='0607')),
                ('lesson_0809', models.CharField(max_length=64, verbose_name='0809')),
                ('lesson_10', models.CharField(max_length=64, verbose_name='10')),
                ('lesson_1112', models.CharField(max_length=64, verbose_name='1112')),
                ('lesson_13', models.CharField(max_length=64, verbose_name='13')),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=32, verbose_name='教室')),
                ('lesson_0102', models.CharField(max_length=64, verbose_name='0102')),
                ('lesson_0304', models.CharField(max_length=64, verbose_name='0304')),
                ('lesson_05', models.CharField(max_length=64, verbose_name='05')),
                ('lesson_0607', models.CharField(max_length=64, verbose_name='0607')),
                ('lesson_0809', models.CharField(max_length=64, verbose_name='0809')),
                ('lesson_10', models.CharField(max_length=64, verbose_name='10')),
                ('lesson_1112', models.CharField(max_length=64, verbose_name='1112')),
                ('lesson_13', models.CharField(max_length=64, verbose_name='13')),
            ],
        ),
    ]
